name: Worker Auto-Updater

on:
  schedule:
    - cron: '0 18 * * *'  # UTC时间18:00 = 北京时间次日02:00
  workflow_dispatch:
    inputs:
      update_mode:
        description: '更新模式 (留空则使用上次配置)'
        required: false
        default: ''
        type: choice
        options:
        - 自动
        - 手动
      release_channel:
        description: '发布渠道 (留空则使用上次配置)'
        required: false
        default: ''
        type: choice
        options:
        - 稳定版
        - 测试版
      deobfuscate:
        description: '反混淆代码 (留空则使用上次配置)'
        required: false
        default: ''
        type: choice
        options:
        - 'true'
        - 'false'

env:
  REPO_URL: https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases
  INSTALL_DIR: .
  DEFAULT_UPDATE_MODE: '自动'
